### PR TITLE
Update binary

### LINKED ISSUE #17: Lambda error on 0.1.2 fork/exec /var/task/AutoSpotting: no such file or directory: PathError null
Deployed the 0.1.2 module and CloudWatch is throwing an error when it triggers

fork/exec /var/task/AutoSpotting: no such file or directory: PathError null

### PR DESCRIPTION
**Pull request by bfin**
Fixes #17

### CODE REVIEW

**Comment by cristim** [comment]
@bfin why not just reference the binary from my S3 bucket? this way it would be always up-to-date.

**Comment by bfin** [comment]
@cristim That would work, with the caveat that the AWS provider region would have to be 'us-east-1' because the lambda function must reside in the same region as the S3 bucket ([docs](https://www.terraform.io/docs/providers/aws/r/lambda_function.html#s3_bucket)). Not quite as smooth for those just testing it out unless they're already using that region, but it's only a few extra lines of code if they're not.

Worst case (using another region), Terraform config would change from this:
```hcl
provider "aws" {
  region  = "us-east-2"
  profile = "default"
}

module "autospotting" {
  source = "github.com/autospotting/terraform-aws-autospotting"
}
```

... to this:

```hcl
provider "aws" {
  region  = "us-east-2"
  profile = "default"
}

provider "aws" {
  alias   = "east1"
  region  = "us-east-1"
  profile = "default"
}

module "autospotting" {
  source = "github.com/autospotting/terraform-aws-autospotting"
  providers = {
    aws = aws.east1
  }
}
```

How would you like to proceed?
(1) Change the default as you suggested (with above caveat and sample added to docs) and remove binary from the repo
(2) Keep current default but document how to use the hosted nightly build

**Comment by cristim** [comment]
I'm in favor of the first option, better to have it work out of the box and have documentation for the few people who really want to have it in another region.

The region where you run it  is not so important so I think for most people us-east-1 should be fine.

**Comment by bfin** [comment]
Ok, now defaults to your S3 bucket.

**Review by cristim — APPROVED** [review]
@bfin Looks great, thanks for your contribution!

**Pull request merged**
